---
title: ""
format:
  html:
    toc: true
execute:
    enabled: true
    echo: false
---

## Curso de grado (recientes)

- **Cálculo Avanzado**. Facultad Regional La Plata, Universidad Tecnológica Nacional. ([web](https://github.com/manuxch/calculo_avanzado)) (2023 -- 2025).

- **Mecánica de Materiales Granulares**. Facultad Regional La Plata, Universidad Tecnológica Nacional. (2018 -- 2022).

- **Física 2**. Facultad Regional Buenos Aires, Universidad Tecnológica Nacional. (2005 -- 2017).

## Cursos de posgrado

- **Herramientas Computacionales para Científicos (HCC)**. Curso de posgrado válido para el doctorado de la Facultad de Ciencias Exactas y Facultad de Ciencias Astronómicas y Geofísicas de la Universidad Nacional de La Plata, y para el doctorado en Ingeniería de la Universidad Tecnológica Nacional. Coordinadores: Dr. Manuel Carlevaro y Dr. Ramiro Irastorza (desde 2018, antes Dr. Luis Pugnaloni).  Duración: 70 horas (2007 -- 2024).

- **Physics and Applications of Granular Matter**. New Jersey Institute of Technology, Department of Mathematical Sciences y Ministerio de Educación de Argentina. Coordinador: Lou Kondic (Distinguished Professor NJIT). Duración: 140 horas (2002).

- **Herramientas computacionales para la mecánica estadística**. Universidad Nacional de La Pampa, Facultad de Ciencias Exactas y Naturales. Responsables: Dr. Luis Pugnaloni,
Dr. Manuel Carlevaro. Duración: 20 horas (2017).

- **Líquidos y Sistemas Desordenados**. Universidad Nacional de San Luis, Facultad de Ciencias Físico Matemáticas y Naturales. Responsables: Dr. Tomás Grigera y Dr. Manuel Carlevaro. Duración: 20 horas (2015).

- **Introducción a Sistemas Dinámicos y Teoría del Caos**. Escuela de Postgrado y Educación Continua. Facultad de Ingeniería, Universidad Nacional de La Plata. Coordinador: Dr. Fernando Vericat. Duración: 60 horas (2007, 2010).

- **Introducción a la programación, al cálculo numérico y a la simulación para científicos**. Instituto de Física de Líquidos y Sistemas Biológicos. Facultad de Ciencias Exactas, Universidad Nacional de La Plata. Coordinadores: Dr. Luis Pugnaloni, Dr. Manuel Carlevaro. Duración: 70 horas (2007).
