---
title: ""
format:
  html:
    toc: true
execute:
    enabled: true
    echo: false
---

## Mini bio

Al finalizar la escuela secundaria en [Paraná](https://es.wikipedia.org/wiki/Paran%C3%A1_(Argentina)), comencé mis estudios universitarios cursando simultáneamente dos carreras: [Ingeniería Electromecánica](https://www.frp.utn.edu.ar/info2/) en la Universidad Tecnológica Nacional, y [Bioingeniería](https://www.ingenieria.uner.edu.ar/) en la Universidad Nacional de Entre Ríos. Pero yo realmente quería estudiar física, por lo que en el año 1990 me mudé a la ciudad de [Rosario](https://es.wikipedia.org/wiki/Rosario_(Argentina)).

Me gradué de Licenciado en Física por la Universidad Nacional de Rosario en 1995, y luego obtuve mi doctorado por la Facultad de Ciencias Exactas de la Universidad Nacional de La Plata en 2002, gracias a una beca doctoral de CONICET.

Después de completar mi doctorado, trabajé como investigador en el Programa de Agronegocios y 
Alimentos de la Universidad de Buenos Aires (2001 -- 2003) realizando modelos computacionales de cadenas agroalimentarias. Posteriormente trabajé en la [Autoridad Regulatoria Nuclear](https://www.argentina.gob.ar/arn) (2003 -- 2007) en proyectos vinculados al [Tratado de Prohibición Completa de Ensayos Nucleares](https://www.ctbto.org/). 

En 2007 ingresé como Investigador Asistente de [CONICET](https://www.conicet.gov.ar/) en el 
[Instituto de Física de Líquidos y Sistemas Biológicos - IFLySiB](https://web.iflysib.unlp.edu.ar/), que depende de CONICET y de la [Universidad Nacional de La Plata](https://unlp.edu.ar/), donde trabajo actualmente, pero ahora como Investigador Independiente.

Como docente trabajé, entre 1993 y 1996, en la Universidad Nacional de Rosario (en las facultades de Ingeniería, Medicina, Veterinaria, y Bioquímica y Farmacia), también en la Facultad de Ciencias Exactas de la Universidad Nacional de La Plata, entre 1997 y 2001. En 2005 comencé como Profesor Adjunto en la Facultad Regional Buenos Aires de la Universidad 
Tecnológica Nacional, dictando la asignatura Física II, y desde 2018 trabajo como Profesor Titular en la Facultad Regional La Plata de la misma universidad, dando cursos de grado (actualmente _Cálculo Avanzado_) y también de posgrado.

---

## Financiamiento

```{python, eval:true, results='asis'}
import yaml

def get_list(file='_data/grants.yaml'):
    with open(file, 'r') as f:
        grants = yaml.safe_load(f)

    html_output = '<ul> \n'
    for grant in grants:
        nombre = grant['name']
        code = grant['code']
        years = grant['period']
        html_output += f"<li> <b>{nombre}</b><br> {code}, {years}"
        html_output += "</li> \n"
    html_output += "</ol>"

    return html_output


from IPython.display import display, HTML
lista = get_list()
display(HTML(lista))

```

---

## Estudiantes

```{python, eval:true, results='asis'}
import yaml

def get_list(file='_data/alumnos.yaml'):
    with open(file, 'r') as f:
        estudiantes = yaml.safe_load(f)

    html_output = '<ul> \n'
    for estudiante in estudiantes:
        nombre = estudiante['name']
        loc = estudiante['location']
        deg = estudiante['degree']
        years = estudiante['year']
        html_output += f"<li> <b>{nombre}</b>: {loc} ({deg}, {years})"
        html_output += "</li> \n"
    html_output += "</ol>" 

    return html_output


from IPython.display import display, HTML
lista = get_list()
display(HTML(lista))

```


